### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by fcvarela**
Py3 support

### CODE REVIEW

**Comment by fcvarela** [comment]
Sorry I messed your request. I just signed it. Cheers!

**Comment by yipjustin** [comment]
Thanks.

**Comment by fcvarela** [comment]
Hi, I noticed the test suite is also py27 only and i'm getting quite a few
errors related to pep8 compliance, import ordering, unused imports, etc.
Would it be ok for me to clean this up a bit and PR back? I could make them
py27/py34 compatible while I'm at it as well.

Cheers,
Filipe

**Comment by dszeto** [comment]
That would be very helpful @fcvarela . Thanks!

**Comment by yipjustin** [comment]
The test suite is actually outdated. It is for PredictionIO pre 0.8's API.

The new version doesn't have a test suite yet. Feel free to update the test suite too. :)

**Comment by fcvarela** [comment]
I just noticed that. I did a flake8/pep8 cleanup on the test suite but none
of the tests pass obviously. Question, is anyone actually using the old
API? If there are currently no tests for >0.8, how worse would it be to
remove the entire test suite for <0.8?

Can I suggest:
1 - Remove all traces of the obsolete package.
2 - Remove all tests using the obsolete <0.8 API
3 - Reimplement same tests for the 0.8 API

I'm not saying this would happen overnight, of course, but I think it's a
good target to aim for.

Cheers

**Comment by fcvarela** [comment]
I'd be very happy to help with with that, of course. Also, is there a set
of Python versions you want to support? I added a tox wrapper with py27 and
py34 which then calls into flake and the test suite. Wondering if you want
more versions there. Also, how about CI and coverage :) ?

Cheers

**Comment by yipjustin** [comment]
Hi Filipe,

Sounds great to have all your suggestions implemented.
1 - Remove all traces of the obsolete package.
2 - Remove all tests using the obsolete <0.8 API
3 - Reimplement same tests for the 0.8 API

Our team don't have the bandwidth to implement these, we are looking forward for contributions. Also, contribution about CI and coverage are welcome!

py27 and py34 should cover most usage.

Thanks.

Justin

**Comment by fcvarela** [comment]
That's great to hear! I have gone ahead and wrapped up 2.7/3.4 and also
linted everything for PEP8. It now passes a flake run from the test
wrapper. And some extra stuff. Anyway, there's a PR ready for you guys to
review. Just let me know if you'd like to me to change anything.

Cheers

**Pull request merged**
