### PR TITLE
Added missing import for InvalidArgumentError

### PR DESCRIPTION
**Pull request by AlmogCohen**
Fix NameError when url provided to client is malformed.

### CODE REVIEW

**Comment by yipjustin** [comment]
Thanks. Before I merge this PR, would you mind signing our CLA?

https://prediction.io/cla

Thanks.

**Comment by AlmogCohen** [comment]
I'm a developer, not yet a lawyer.
I've read it but its too long for me to know what complications it can bring upon me.

I would really like to contribute to PredictionIO in the future, and I really like the project, but currently its too much for me to sign contracts with PredictionIO.

**Comment by AlmogCohen** [comment]
You aren't going to accept this?....

**Comment by EmergentOrder** [comment]
accepted. Thanks @AlmogCohen !

**Pull request merged**
